package com.reservita.demo.modelo;
// Generated 2/07/2017 03:41:39 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private Mesa mesa;
     private Usuario usuario;
     private Date fechaReserva;
     private Integer idMesa;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Menu> menus = new HashSet<Menu>(0);

    public Reserva() {
    }

	
    public Reserva(Mesa mesa, Usuario usuario) {
        this.mesa = mesa;
        this.usuario = usuario;
    }
    public Reserva(Mesa mesa, Usuario usuario, Date fechaReserva, Integer idMesa, Set<Factura> facturas, Set<Menu> menus) {
       this.mesa = mesa;
       this.usuario = usuario;
       this.fechaReserva = fechaReserva;
       this.idMesa = idMesa;
       this.facturas = facturas;
       this.menus = menus;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaReserva() {
        return this.fechaReserva;
    }
    
    public void setFechaReserva(Date fechaReserva) {
        this.fechaReserva = fechaReserva;
    }
    public Integer getIdMesa() {
        return this.idMesa;
    }
    
    public void setIdMesa(Integer idMesa) {
        this.idMesa = idMesa;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Menu> getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set<Menu> menus) {
        this.menus = menus;
    }




}


